version: '3'

services:
  notification-demo:
    build: 
      context: ./notification-demo
      dockerfile: Dockerfile
    ports:
      - "9100:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - app-network

  like-app:
    build: 
      context: ./like-app
      dockerfile: Dockerfile
    ports:
      - "9101:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge