version: '3'

services:
  notification-demo:
    build: 
      context: ./notification-demo
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    environment:
      - REDIS_URL=redis://redis:6379

  like-app:
    build: 
      context: ./like-app
      dockerfile: Dockerfile
    ports:
      - "9101:9101"
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"